"""
Tools available to the Security Prover agent.

file_read             — built-in strands_tools; lets the LLM read .tf files.
file_write            — built-in strands_tools; lets the LLM write Rego files.
generate_rego_suite   — parses I-IR and writes focused Rego files per rule group.
run_encryption_check  — conftest/Python check for encryption rules.
run_network_check     — conftest/Python check for network/ingress rules.
run_access_check      — conftest/Python check for IAM/secret access rules.
run_governance_check  — conftest/Python check for tagging and residency rules.
run_scanner_check     — optional Checkov/Regula scanner cross-check.

LLM call sequence:
  Turn 1: generate_rego_suite (writes policy files)
  Turn 2: run_encryption_check + run_network_check + run_access_check +
          run_governance_check + run_scanner_check (parallel)
"""
from __future__ import annotations

import json
import os
import re
import subprocess
from typing import Any

from strands import tool, ToolContext
from strands_tools import file_read, file_write  # noqa: F401

from agents._rtk import wrap_cmd


# ── Rego templates ────────────────────────────────────────────────────────────

_ENCRYPTION_REGO = """\
package main

# Generated by MACOG Security Prover — encryption rule group
# effects: encrypt_at_rest

deny[msg] {{
    resource := input.resource.aws_s3_bucket[name]
    not resource.server_side_encryption_configuration
    msg := sprintf("aws_s3_bucket.%v: missing server_side_encryption_configuration", [name])
}}

deny[msg] {{
    resource := input.resource.aws_db_instance[name]
    not resource.storage_encrypted == true
    msg := sprintf("aws_db_instance.%v: missing storage_encrypted = true", [name])
}}

deny[msg] {{
    resource := input.resource.aws_ebs_volume[name]
    not resource.encrypted == true
    msg := sprintf("aws_ebs_volume.%v: missing encrypted = true", [name])
}}
"""

_NETWORK_REGO = """\
package main

# Generated by MACOG Security Prover — network rule group
# effects: restricted_ingress

deny[msg] {{
    resource := input.resource.aws_security_group[name]
    ingress := resource.ingress[_]
    cidr := ingress.cidr_blocks[_]
    cidr == "0.0.0.0/0"
    msg := sprintf("aws_security_group.%v: unrestricted ingress 0.0.0.0/0", [name])
}}

deny[msg] {{
    resource := input.resource.aws_db_instance[name]
    resource.publicly_accessible == true
    msg := sprintf("aws_db_instance.%v: publicly_accessible must be false", [name])
}}
"""

_ACCESS_REGO = """\
package main

# Generated by MACOG Security Prover — access rule group
# effects: least_privilege, no_hardcoded_secrets

deny[msg] {{
    resource := input.resource.aws_iam_policy[name]
    doc := json.unmarshal(resource.policy)
    statement := doc.Statement[_]
    statement.Action == "*"
    msg := sprintf("aws_iam_policy.%v: wildcard Action in IAM policy", [name])
}}

deny[msg] {{
    resource := input.resource.aws_iam_policy[name]
    doc := json.unmarshal(resource.policy)
    statement := doc.Statement[_]
    statement.Resource == "*"
    msg := sprintf("aws_iam_policy.%v: wildcard Resource in IAM policy", [name])
}}
"""

_GOVERNANCE_REGO = """\
package main

# Generated by MACOG Security Prover — governance rule group
# effects: tag_required, residency_eu

taggable_types := {
    "aws_instance",
    "aws_vpc",
    "aws_subnet",
    "aws_db_instance",
    "aws_s3_bucket",
    "aws_lb",
    "aws_security_group",
}

deny[msg] {
    resources := input.resource[type]
    taggable_types[type]
    resource := resources[name]
    not resource.tags
    msg := sprintf("%v.%v: missing tags block", [type, name])
}

deny[msg] {
    resources := input.resource[type]
    taggable_types[type]
    resource := resources[name]
    resource.tags
    not resource.tags.Environment
    msg := sprintf("%v.%v: missing Environment tag", [type, name])
}
"""


# ── Tool: generate_rego_suite ─────────────────────────────────────────────────

@tool(context=True)
def generate_rego_suite(
    session_dir: str = "",
    iir_json: str = "",
    tool_context: ToolContext = None,
) -> str:
    """
    Parse I-IR effects and resource list; generate focused Rego policy files in
    {session_dir}/policy/ — one file per rule group (encryption, network, access, governance).

    Detects which rule groups apply from iir_json effects or from HCL resource types.
    Only writes rule groups that are relevant to the detected resources.

    Writes state key: rego_files.
    Returns JSON: {policy_files, effects_detected, logs}.
    """
    if not session_dir or not os.path.isdir(session_dir):
        return json.dumps({"policy_files": [], "effects_detected": [],
                           "logs": "No valid session_dir provided"})

    logs: list[str] = []
    effects: list[str] = []
    resource_types: list[str] = []

    # Parse I-IR for effects and resource types
    if iir_json:
        try:
            iir = json.loads(iir_json)
            nodes = iir.get("nodes", iir.get("resources", []))
            for node in nodes:
                rtype = node.get("resource_type", node.get("kind", node.get("type", "")))
                if rtype:
                    resource_types.append(rtype)
                effs = node.get("effects", node.get("specs", {}).get("effects", []))
                if isinstance(effs, list):
                    effects.extend(effs)
                elif isinstance(effs, str):
                    effects.extend(e.strip() for e in effs.split(",") if e.strip())
            logs.append(f"Parsed I-IR: {len(nodes)} resources, effects={effects}")
        except (json.JSONDecodeError, KeyError, TypeError) as exc:
            logs.append(f"I-IR parse error: {exc}; falling back to HCL scan")

    # Fallback: derive from HCL
    if not resource_types and not effects:
        hcl = _read_tf_dir(session_dir)
        for rtype in ("aws_s3_bucket", "aws_db_instance", "aws_ebs_volume",
                       "aws_security_group", "aws_iam_policy", "aws_instance"):
            if rtype in hcl:
                resource_types.append(rtype)
        if any(r in resource_types for r in ("aws_s3_bucket", "aws_db_instance", "aws_ebs_volume")):
            effects.append("encrypt_at_rest")
        if "aws_security_group" in resource_types or "aws_db_instance" in resource_types:
            effects.append("restricted_ingress")
        if "aws_iam_policy" in resource_types:
            effects.append("least_privilege")
        if any(r.startswith("aws_") for r in resource_types):
            effects.append("tag_required")
        logs.append(f"HCL scan: resource_types={resource_types}, effects={effects}")

    # Determine which rule groups to write
    write_encryption = (
        "encrypt_at_rest" in effects
        or any(r in resource_types for r in ("aws_s3_bucket", "aws_db_instance", "aws_ebs_volume"))
    )
    write_network = (
        "restricted_ingress" in effects or "least_privilege" in effects
        or any(r in resource_types for r in ("aws_security_group", "aws_db_instance"))
    )
    write_access = (
        "least_privilege" in effects or "no_hardcoded_secrets" in effects
        or "aws_iam_policy" in resource_types
        or True  # always check for hardcoded secrets
    )
    write_governance = (
        "tag_required" in effects
        or "residency_eu" in effects
        or any(r.startswith("aws_") for r in resource_types)
    )

    policy_dir = os.path.join(session_dir, "policy")
    os.makedirs(policy_dir, exist_ok=True)

    policy_files: list[dict] = []

    if write_encryption:
        path = os.path.join(policy_dir, "encryption.rego")
        with open(path, "w") as fh:
            fh.write(_ENCRYPTION_REGO)
        policy_files.append({"path": path, "rule_group": "encryption"})
        logs.append("Wrote encryption.rego")

    if write_network:
        path = os.path.join(policy_dir, "network.rego")
        with open(path, "w") as fh:
            fh.write(_NETWORK_REGO)
        policy_files.append({"path": path, "rule_group": "network"})
        logs.append("Wrote network.rego")

    if write_access:
        path = os.path.join(policy_dir, "access.rego")
        with open(path, "w") as fh:
            fh.write(_ACCESS_REGO)
        policy_files.append({"path": path, "rule_group": "access"})
        logs.append("Wrote access.rego")

    if write_governance:
        path = os.path.join(policy_dir, "governance.rego")
        with open(path, "w") as fh:
            fh.write(_GOVERNANCE_REGO)
        policy_files.append({"path": path, "rule_group": "governance"})
        logs.append("Wrote governance.rego")

    if tool_context is not None:
        tool_context.agent.state.set("rego_files", json.dumps(policy_files))

    return json.dumps({
        "policy_files": policy_files,
        "effects_detected": list(set(effects)),
        "logs": "\n".join(logs),
    })


# ── Tool: run_encryption_check ────────────────────────────────────────────────

@tool(context=True)
def run_encryption_check(
    session_dir: str = "",
    tool_context: ToolContext = None,
) -> str:
    """
    Run conftest against encryption.rego; falls back to Python encrypt rules.

    Checks: S3 SSE, RDS storage_encrypted, EBS encrypted.
    Writes state key: encryption_violations.
    Returns JSON: {violations, proof_traces, source}.
    """
    result = _run_rule_group_check(
        session_dir=session_dir,
        rego_filename="encryption.rego",
        python_checker=_python_encryption_check,
    )
    if tool_context is not None:
        tool_context.agent.state.set(
            "encryption_violations", json.dumps(result.get("violations", []))
        )
    return json.dumps(result)


# ── Tool: run_network_check ───────────────────────────────────────────────────

@tool(context=True)
def run_network_check(
    session_dir: str = "",
    tool_context: ToolContext = None,
) -> str:
    """
    Run conftest against network.rego; falls back to Python network rules.

    Checks: 0.0.0.0/0 cidr_blocks in security groups, publicly_accessible RDS.
    Writes state key: network_violations.
    Returns JSON: {violations, proof_traces, source}.
    """
    result = _run_rule_group_check(
        session_dir=session_dir,
        rego_filename="network.rego",
        python_checker=_python_network_check,
    )
    if tool_context is not None:
        tool_context.agent.state.set(
            "network_violations", json.dumps(result.get("violations", []))
        )
    return json.dumps(result)


# ── Tool: run_access_check ────────────────────────────────────────────────────

@tool(context=True)
def run_access_check(
    session_dir: str = "",
    tool_context: ToolContext = None,
) -> str:
    """
    Run conftest against access.rego; falls back to Python access rules.

    Checks: hardcoded secrets regex, wildcard IAM Action/Resource.
    Writes state key: access_violations.
    Returns JSON: {violations, proof_traces, source}.
    """
    result = _run_rule_group_check(
        session_dir=session_dir,
        rego_filename="access.rego",
        python_checker=_python_access_check,
    )
    if tool_context is not None:
        tool_context.agent.state.set(
            "access_violations", json.dumps(result.get("violations", []))
        )
    return json.dumps(result)


# ── Tool: run_governance_check ────────────────────────────────────────────────

@tool(context=True)
def run_governance_check(
    session_dir: str = "",
    constraints_json: str = "{}",
    tool_context: ToolContext = None,
) -> str:
    """
    Run conftest against governance.rego; falls back to Python governance rules.

    Checks: required tags on taggable resources and region/data-residency allow-list.
    Writes state key: governance_violations.
    Returns JSON: {violations, proof_traces, source}.
    """
    constraints: dict[str, Any] = {}
    if constraints_json:
        try:
            constraints = json.loads(constraints_json)
        except json.JSONDecodeError:
            constraints = {}
    result = _run_rule_group_check(
        session_dir=session_dir,
        rego_filename="governance.rego",
        python_checker=lambda hcl: _python_governance_check(hcl, constraints),
    )
    if tool_context is not None:
        tool_context.agent.state.set(
            "governance_violations", json.dumps(result.get("violations", []))
        )
    return json.dumps(result)


# ── Tool: run_scanner_check ───────────────────────────────────────────────────

@tool(context=True)
def run_scanner_check(
    session_dir: str = "",
    strict: bool = False,
    tool_context: ToolContext = None,
) -> str:
    """
    Run optional third-party scanners, mirroring the paper's Checkov/Regula cross-check.

    Returns pass with source=unavailable when neither scanner is installed.
    By default, third-party scanner findings are advisory because generic
    Checkov/Regula packs include organization-specific hardening rules beyond
    the user's stated constraints. Set strict=true to make findings blocking.
    Writes state key: scanner_violations.
    """
    result = _run_external_scanners(session_dir, strict=strict)
    if tool_context is not None:
        tool_context.agent.state.set(
            "scanner_violations", json.dumps(result.get("violations", []))
        )
    return json.dumps(result)


# ── Shared dispatcher ─────────────────────────────────────────────────────────

def _run_rule_group_check(
    session_dir: str,
    rego_filename: str,
    python_checker,
) -> dict[str, Any]:
    """Try conftest for a specific Rego file; fall back to python_checker."""
    if not session_dir or not os.path.isdir(session_dir):
        return {
            "violations": [{"rule": "input_error", "severity": "critical",
                            "message": "No valid session_dir provided"}],
            "proof_traces": [],
            "source": "error",
        }

    tf_files = [
        os.path.join(session_dir, f)
        for f in sorted(os.listdir(session_dir))
        if f.endswith(".tf")
    ]
    hcl = _read_tf_dir(session_dir)

    policy_path = os.path.join(session_dir, "policy", rego_filename)

    python_result = python_checker(hcl)

    if os.path.isfile(policy_path):
        try:
            proc = subprocess.run(
                wrap_cmd(["conftest", "test", "--policy", policy_path,
                 "--format", "json", "--no-color"] + tf_files),
                capture_output=True, text=True, timeout=60,
            )
            if proc.stdout:
                return _merge_policy_results(_parse_conftest_output(proc.stdout), python_result)
        except FileNotFoundError:
            pass  # conftest not installed
        except subprocess.TimeoutExpired:
            pass

    return python_result


def _merge_policy_results(primary: dict[str, Any], complement: dict[str, Any]) -> dict[str, Any]:
    """Merge OPA/conftest and Python scanner output to reduce false negatives."""
    violations = primary.get("violations", []) + complement.get("violations", [])
    proof_traces = primary.get("proof_traces", []) + complement.get("proof_traces", [])
    seen: set[tuple[str, str, str]] = set()
    deduped: list[dict] = []
    for violation in violations:
        key = (
            violation.get("rule", ""),
            violation.get("resource", ""),
            violation.get("message", ""),
        )
        if key in seen:
            continue
        seen.add(key)
        deduped.append(violation)
    has_blocking = any(v.get("severity") in ("critical", "high") for v in deduped)
    return {
        "v_policy": 0 if has_blocking else 1,
        "violations": deduped,
        "proof_traces": proof_traces,
        "source": f"{primary.get('source', 'primary')}+{complement.get('source', 'python')}",
    }


def _parse_conftest_output(raw: str) -> dict[str, Any]:
    violations: list[dict] = []
    proof_traces: list[dict] = []
    try:
        results = json.loads(raw)
        for file_result in results:
            fname = file_result.get("filename", "")
            for failure in file_result.get("failures", []):
                msg = failure.get("msg", "")
                violations.append({
                    "rule": "opa_policy", "resource": fname, "severity": "high",
                    "message": msg,
                    "counterexample": {"type": "policy", "rule": "opa_policy", "resource": fname},
                    "fix": "Review Rego policy and fix the flagged resource",
                })
                proof_traces.append({"rule": "opa_policy", "status": "fail", "detail": msg})
            for warning in file_result.get("warnings", []):
                msg = warning.get("msg", "")
                violations.append({
                    "rule": "opa_warning", "resource": fname, "severity": "medium",
                    "message": msg,
                    "counterexample": {"type": "policy", "rule": "opa_warning", "resource": fname},
                    "fix": "Review Rego policy warning",
                })
                proof_traces.append({"rule": "opa_warning", "status": "warn", "detail": msg})
            successes = file_result.get("successes", 0)
            if successes and successes > 0:
                proof_traces.append({
                    "rule": "opa_policy", "status": "pass",
                    "detail": f"{successes} checks passed in {fname}",
                })
    except (json.JSONDecodeError, KeyError):
        pass
    has_blocking = any(v["severity"] in ("critical", "high") for v in violations)
    v_policy = 0 if has_blocking else 1  # paper eq.(2): v_policy ∈ {0,1}
    return {"v_policy": v_policy, "violations": violations, "proof_traces": proof_traces,
            "source": "conftest"}


# ── Python fallback checkers per rule group ────────────────────────────────────

def _python_encryption_check(hcl: str) -> dict[str, Any]:
    violations: list[dict] = []
    proof_traces: list[dict] = []

    def _fail(rule: str, resource: str, msg: str, fix: str) -> None:
        violations.append({
            "rule": rule, "resource": resource, "severity": "high", "message": msg,
            "counterexample": {"type": "policy", "rule": rule, "resource": resource},
            "fix": fix,
        })
        proof_traces.append({"rule": rule, "status": "fail"})

    def _pass(rule: str) -> None:
        if not any(t["rule"] == rule for t in proof_traces):
            proof_traces.append({"rule": rule, "status": "pass"})

    if "aws_s3_bucket" in hcl:
        if ("server_side_encryption_configuration" not in hcl
                and "aws_s3_bucket_server_side_encryption_configuration" not in hcl):
            _fail("encrypt_at_rest", "aws_s3_bucket",
                  "S3 bucket missing server-side encryption",
                  "Add aws_s3_bucket_server_side_encryption_configuration resource")
        else:
            _pass("encrypt_at_rest_s3")

    if "aws_db_instance" in hcl:
        if not re.search(r'storage_encrypted\s*=\s*true', hcl):
            _fail("encrypt_at_rest", "aws_db_instance",
                  "RDS instance missing storage_encrypted = true",
                  "Add storage_encrypted = true to aws_db_instance block")
        else:
            _pass("encrypt_at_rest_rds")

    if "aws_ebs_volume" in hcl:
        if not re.search(r'encrypted\s*=\s*true', hcl):
            _fail("encrypt_at_rest", "aws_ebs_volume",
                  "EBS volume missing encrypted = true",
                  "Add encrypted = true to aws_ebs_volume block")
        else:
            _pass("encrypt_at_rest_ebs")

    if not violations:
        _pass("encrypt_at_rest")

    has_blocking = any(v["severity"] in ("critical", "high") for v in violations)
    v_policy = 0 if has_blocking else 1  # paper eq.(2): v_policy ∈ {0,1}
    return {"v_policy": v_policy, "violations": violations, "proof_traces": proof_traces,
            "source": "python"}


def _python_network_check(hcl: str) -> dict[str, Any]:
    violations: list[dict] = []
    proof_traces: list[dict] = []

    def _fail(rule: str, resource: str, msg: str, fix: str) -> None:
        violations.append({
            "rule": rule, "resource": resource, "severity": "high", "message": msg,
            "counterexample": {"type": "policy", "rule": rule, "resource": resource},
            "fix": fix,
        })
        proof_traces.append({"rule": rule, "status": "fail"})

    def _pass(rule: str) -> None:
        if not any(t["rule"] == rule for t in proof_traces):
            proof_traces.append({"rule": rule, "status": "pass"})

    if re.search(r'cidr_blocks\s*=\s*\["0\.0\.0\.0/0"\]', hcl):
        _fail("restricted_ingress", "aws_security_group",
              "Security group allows unrestricted ingress 0.0.0.0/0",
              "Restrict cidr_blocks to specific CIDR ranges")
    else:
        _pass("restricted_ingress")

    if "aws_db_instance" in hcl:
        if re.search(r'publicly_accessible\s*=\s*true', hcl):
            _fail("no_public_rds", "aws_db_instance",
                  "RDS instance is publicly accessible",
                  "Set publicly_accessible = false")
        else:
            _pass("no_public_rds")

    has_blocking = any(v["severity"] in ("critical", "high") for v in violations)
    v_policy = 0 if has_blocking else 1  # paper eq.(2): v_policy ∈ {0,1}
    return {"v_policy": v_policy, "violations": violations, "proof_traces": proof_traces,
            "source": "python"}


def _python_access_check(hcl: str) -> dict[str, Any]:
    violations: list[dict] = []
    proof_traces: list[dict] = []

    def _fail(rule: str, resource: str, msg: str, fix: str, severity: str = "high") -> None:
        violations.append({
            "rule": rule, "resource": resource, "severity": severity, "message": msg,
            "counterexample": {"type": "policy", "rule": rule, "resource": resource},
            "fix": fix,
        })
        proof_traces.append({"rule": rule, "status": "fail"})

    def _pass(rule: str) -> None:
        if not any(t["rule"] == rule for t in proof_traces):
            proof_traces.append({"rule": rule, "status": "pass"})

    secret_rx = [
        r'(?i)(password|secret|api_key|private_key)\s*=\s*"[^$"][^"]{7,}"',
        r'(?i)aws_access_key_id\s*=\s*"AKIA[A-Z0-9]{16}"',
        r'(?i)aws_secret_access_key\s*=\s*"[A-Za-z0-9/+]{40}"',
    ]
    if any(re.search(p, hcl) for p in secret_rx):
        _fail("no_hardcoded_secrets", "", "Hardcoded credential detected in HCL",
              "Use var.xxx references or aws_secretsmanager_secret_version data sources",
              severity="critical")
    else:
        _pass("no_hardcoded_secrets")

    if re.search(r'"Action"\s*:\s*"\*"', hcl) or re.search(r'"Resource"\s*:\s*"\*"', hcl):
        _fail("least_privilege", "aws_iam_policy",
              "IAM policy uses wildcard Action or Resource (*)",
              "Replace * with specific actions and resource ARNs")
    else:
        _pass("least_privilege")

    has_blocking = any(v["severity"] in ("critical", "high") for v in violations)
    v_policy = 0 if has_blocking else 1  # paper eq.(2): v_policy ∈ {0,1}
    return {"v_policy": v_policy, "violations": violations, "proof_traces": proof_traces,
            "source": "python"}


def _python_governance_check(hcl: str, constraints: dict[str, Any]) -> dict[str, Any]:
    violations: list[dict] = []
    proof_traces: list[dict] = []
    taggable = {
        "aws_instance", "aws_vpc", "aws_subnet", "aws_db_instance",
        "aws_s3_bucket", "aws_lb", "aws_security_group",
    }

    def _fail(rule: str, resource: str, msg: str, fix: str, severity: str = "high") -> None:
        violations.append({
            "rule": rule, "resource": resource, "severity": severity, "message": msg,
            "counterexample": {"type": "policy", "rule": rule, "resource": resource},
            "fix": fix,
        })
        proof_traces.append({"rule": rule, "status": "fail"})

    def _pass(rule: str) -> None:
        if not any(t["rule"] == rule for t in proof_traces):
            proof_traces.append({"rule": rule, "status": "pass"})

    for rtype, rname, body in _resource_blocks(hcl):
        if rtype not in taggable:
            continue
        if "tags" not in body:
            _fail("tag_required", f"{rtype}.{rname}",
                  "Taggable resource is missing a tags block",
                  "Add tags = { Name = \"...\", Environment = var.environment }")
        elif "Environment" not in body:
            _fail("tag_required", f"{rtype}.{rname}",
                  "Taggable resource is missing Environment tag",
                  "Add Environment = var.environment to tags")
    if not any(v["rule"] == "tag_required" for v in violations):
        _pass("tag_required")

    allowed_regions = constraints.get("regions") or constraints.get("allowed_regions") or []
    if isinstance(allowed_regions, str):
        allowed_regions = [allowed_regions]
    configured_regions = set(re.findall(r'\bregion\s*=\s*"([^"]+)"', hcl))
    if allowed_regions and configured_regions:
        disallowed = sorted(region for region in configured_regions if region not in allowed_regions)
        for region in disallowed:
            _fail("data_residency", "provider.aws",
                  f"Configured AWS region {region} is outside allowed regions {allowed_regions}",
                  "Change provider region or pass an allowed region in constraints")
    if allowed_regions and not configured_regions:
        _fail("data_residency", "provider.aws",
              "No explicit provider region found for residency-constrained deployment",
              "Add provider region from constraints or variable validation")
    elif not any(v["rule"] == "data_residency" for v in violations):
        _pass("data_residency")

    has_blocking = any(v["severity"] in ("critical", "high") for v in violations)
    return {
        "v_policy": 0 if has_blocking else 1,
        "violations": violations,
        "proof_traces": proof_traces,
        "source": "python",
    }


def _run_external_scanners(session_dir: str, strict: bool = False) -> dict[str, Any]:
    if not session_dir or not os.path.isdir(session_dir):
        return {
            "v_policy": 0,
            "violations": [{
                "rule": "scanner_input_error",
                "severity": "critical",
                "message": "No valid session_dir provided",
                "fix": "Pass a session directory containing Terraform files",
            }],
            "proof_traces": [],
            "source": "scanner",
        }

    scanner_results = [_run_checkov(session_dir, strict=strict), _run_regula(session_dir, strict=strict)]
    available = [r for r in scanner_results if r["source"] != "unavailable"]
    if not available:
        return {
            "v_policy": 1,
            "violations": [],
            "proof_traces": [{"rule": "scanner_cross_check", "status": "pass"}],
            "source": "unavailable",
        }
    merged = {"v_policy": 1, "violations": [], "proof_traces": [], "source": "+".join(r["source"] for r in available)}
    for result in available:
        merged["violations"].extend(result.get("violations", []))
        merged["proof_traces"].extend(result.get("proof_traces", []))
    if strict and any(v.get("severity") in ("critical", "high") for v in merged["violations"]):
        merged["v_policy"] = 0
    return merged


def _run_checkov(session_dir: str, strict: bool = False) -> dict[str, Any]:
    try:
        proc = subprocess.run(
            wrap_cmd(["checkov", "-d", session_dir, "-o", "json", "--quiet"]),
            capture_output=True, text=True, timeout=120,
        )
    except FileNotFoundError:
        return {"source": "unavailable", "violations": [], "proof_traces": []}
    except subprocess.TimeoutExpired:
        return {
            "source": "checkov",
            "violations": [{
                "rule": "checkov_timeout",
                "severity": "medium",
                "message": "Checkov timed out",
                "fix": "Run Checkov separately with a larger timeout",
            }],
            "proof_traces": [{"rule": "checkov", "status": "warn"}],
        }
    violations: list[dict] = []
    try:
        data = json.loads(proc.stdout or "{}")
        failed = data.get("results", {}).get("failed_checks", [])
        for check in failed:
            violations.append({
                "rule": check.get("check_id", "checkov"),
                "resource": check.get("resource", ""),
                "severity": "high" if strict else "medium",
                "message": check.get("check_name", "Checkov policy failed"),
                "counterexample": {"type": "policy", "rule": check.get("check_id", "checkov")},
                "fix": check.get("guideline", "Review Checkov finding and update Terraform"),
            })
    except json.JSONDecodeError:
        if proc.returncode != 0:
            violations.append({
                "rule": "checkov_parse_error",
                "severity": "medium",
                "message": (proc.stderr or proc.stdout)[:300],
                "fix": "Review Checkov output",
            })
    return {
        "source": "checkov",
        "v_policy": 0 if strict and violations else 1,
        "violations": violations,
        "proof_traces": [{"rule": "checkov", "status": "fail" if violations else "pass"}],
    }


def _run_regula(session_dir: str, strict: bool = False) -> dict[str, Any]:
    try:
        proc = subprocess.run(
            wrap_cmd(["regula", "run", "--format", "json", session_dir]),
            capture_output=True, text=True, timeout=120,
        )
    except FileNotFoundError:
        return {"source": "unavailable", "violations": [], "proof_traces": []}
    except subprocess.TimeoutExpired:
        return {
            "source": "regula",
            "violations": [{
                "rule": "regula_timeout",
                "severity": "medium",
                "message": "Regula timed out",
                "fix": "Run Regula separately with a larger timeout",
            }],
            "proof_traces": [{"rule": "regula", "status": "warn"}],
        }
    violations: list[dict] = []
    try:
        data = json.loads(proc.stdout or "[]")
        results = data if isinstance(data, list) else data.get("rule_results", [])
        for item in results:
            if item.get("result") in ("PASS", "pass", True):
                continue
            violations.append({
                "rule": item.get("rule_id", item.get("name", "regula")),
                "resource": item.get("resource_id", ""),
                "severity": "high" if strict else "medium",
                "message": item.get("message", "Regula policy failed"),
                "counterexample": {"type": "policy", "rule": item.get("rule_id", "regula")},
                "fix": "Review Regula finding and update Terraform",
            })
    except json.JSONDecodeError:
        if proc.returncode != 0:
            violations.append({
                "rule": "regula_parse_error",
                "severity": "medium",
                "message": (proc.stderr or proc.stdout)[:300],
                "fix": "Review Regula output",
            })
    return {
        "source": "regula",
        "v_policy": 0 if strict and violations else 1,
        "violations": violations,
        "proof_traces": [{"rule": "regula", "status": "fail" if violations else "pass"}],
    }


# ── Internal helpers ──────────────────────────────────────────────────────────

def _read_tf_dir(directory: str) -> str:
    parts: list[str] = []
    for fname in sorted(os.listdir(directory)):
        if fname.endswith(".tf"):
            with open(os.path.join(directory, fname)) as fh:
                parts.append(fh.read())
    return "\n".join(parts)


def _resource_blocks(hcl: str) -> list[tuple[str, str, str]]:
    blocks: list[tuple[str, str, str]] = []
    rx = re.compile(r'resource\s+"([A-Za-z0-9_]+)"\s+"([A-Za-z0-9_]+)"\s*\{')
    for match in rx.finditer(hcl):
        start = match.end()
        depth = 1
        i = start
        while i < len(hcl) and depth:
            if hcl[i] == "{":
                depth += 1
            elif hcl[i] == "}":
                depth -= 1
            i += 1
        blocks.append((match.group(1), match.group(2), hcl[start : i - 1]))
    return blocks
